arch = [
  # System Base
  "base",
  "base-devel",
  "linux",
  "linux-firmware",
  "linux-headers",
  "linux-zen",
  "linux-zen-headers",
  "intel-ucode",

  # Boot
  "efibootmgr",
  "grub",
  "grub-btrfs",
  "btrfs-progs",
  "sbctl",
]
