arch = [
  # Login Manager
  {package = "sddm", hooks = { after_install = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "sddm.service",
  ]}},

  # Desktop Environment
  "cinnamon",
  "hyprland",
  "qtile",

  # Appearance
  "bibata-cursor-theme",
  "kora-icon-theme",
  "orchis-theme",
  "ttf-firacode-nerd",
]
