arch = [
  { package = "acpid", hooks = { after_install = [
    "sudo",
    "systemctl",
    "enable",
    "--now",
    "acpid.service",
  ]}},
  "github-cli",
  "rsync",
  "stow",
  "sudo",
  "paru-bin",
  "paru-bin-debug",
  "metapac",
  "timeshift",
  "timeshift-autosnap",
  "zram-generator",
]
