# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [0,1,4]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = false
title_format = "ÔÅª {cwd}"

[preview]
wrap = "no"
tab_size = 2
line_numbers = true

[plugin]
prepend_previewers = [
  { mime = "text/*", run = 'piper -- bat --color=always --style=plain "$1"' },
  { url = "*/", run = 'piper -- eza -l --git --color=always --icons=always --group-directories-first --no-quotes "$1"'},
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
  { url = "*.csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
  { url = "*.xlsx", run = "duckdb" },
  { url = "*.db", run = "duckdb" },
  { url = "*.duckdb", run = "duckdb" },
  { url = "*.{md,markdown}", run = 'piper -- glow "$1"' },
  { url = "*.pdf", run = 'piper -- tdf "$1"'}

]
prepend_fetchers = [
  { id = "git", url = "*", run = "git" },
  { id = "git", url = "*/", run = "git" }
]
