# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [0,1,4]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = false
title_format = "ÔÅª {cwd}"

[preview]
wrap = "no"
tab_size = 2
line_numbers = true

[plugin]
prepend_previewers = [
  { name = "*.md", run = "mdcat" },
  { name = "*.markdown", run = "mdcat" },
]
prepend_fetchers = [
  { id = "git", url = "*", run = "git" },
  { id = "git", url = "*/", run = "git" }
]
